CREATE DATABASE deegree_inspire_cp WITH OWNER=deegree TEMPLATE=postgis_template;
\c deegree_inspire_cp


CREATE TABLE au_administrativeboundary (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    au_geometry_attr_nilreason text,
    au_geometry_attr_gml_remoteschema text,
    au_geometry_attr_owns boolean,
    au_inspireid_base_identifier_base_localid text,
    au_inspireid_base_identifier_base_namespace text,
    au_inspireid_base_identifier_base_versionid text,
    au_inspireid_base_identifier_base_versionid_attr_nilreason text,
    au_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    au_country_attr_gco_nilreason text,
    au_country_gmd_country text,
    au_country_gmd_country_attr_codelist text,
    au_country_gmd_country_attr_codelistvalue text,
    au_country_gmd_country_attr_codespace text,
    au_legalstatus text,
    au_legalstatus_attr_nilreason text,
    au_legalstatus_attr_xsi_nil boolean,
    au_technicalstatus text,
    au_technicalstatus_attr_nilreason text,
    au_technicalstatus_attr_xsi_nil boolean,
    au_beginlifespanversion timestamp,
    au_beginlifespanversion_attr_nilreason text,
    au_beginlifespanversion_attr_xsi_nil boolean,
    au_endlifespanversion timestamp,
    au_endlifespanversion_attr_nilreason text,
    au_endlifespanversion_attr_xsi_nil boolean,
    CONSTRAINT au_administrativeboundary_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'au_administrativeboundary','au_geometry_value','0','GEOMETRY', 2);
CREATE TABLE au_administrativeboundary_au_nationallevel (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeboundary ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    fk text,
    href text
);
CREATE TABLE au_administrativeboundary_au_admunit (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeboundary ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    au_geometry_attr_nilreason text,
    au_geometry_attr_gml_remoteschema text,
    au_geometry_attr_owns boolean,
    au_nationalcode text,
    au_inspireid_base_identifier_base_localid text,
    au_inspireid_base_identifier_base_namespace text,
    au_inspireid_base_identifier_base_versionid text,
    au_inspireid_base_identifier_base_versionid_attr_nilreason text,
    au_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    au_nationallevel_attr_owns boolean,
    au_nationallevel_attr_nilreason text,
    au_nationallevel_attr_gml_remoteschema text,
    au_nationallevel_fk text,
    au_nationallevel_href text,
    au_country_attr_gco_nilreason text,
    au_country_gmd_country text,
    au_country_gmd_country_attr_codelist text,
    au_country_gmd_country_attr_codelistvalue text,
    au_country_gmd_country_attr_codespace text,
    au_beginlifespanversion timestamp,
    au_beginlifespanversion_attr_nilreason text,
    au_beginlifespanversion_attr_xsi_nil boolean,
    au_endlifespanversion timestamp,
    au_endlifespanversion_attr_nilreason text,
    au_endlifespanversion_attr_xsi_nil boolean,
    au_upperlevelunit_attr_owns boolean,
    au_upperlevelunit_attr_nilreason text,
    au_upperlevelunit_attr_gml_remoteschema text,
    au_upperlevelunit_attr_xsi_nil boolean,
    au_upperlevelunit_fk text,
    au_upperlevelunit_href text,
    CONSTRAINT au_administrativeunit_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'au_administrativeunit','au_geometry_value','0','GEOMETRY', 2);
CREATE TABLE au_administrativeunit_au_nationallevelname (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_xlink_type text,
    attr_xlink_href text,
    attr_xlink_role text,
    attr_xlink_arcrole text,
    attr_xlink_title text,
    attr_xlink_show text,
    attr_xlink_actuate text,
    attr_uuidref text,
    attr_gco_nilreason text,
    attr_xsi_nil boolean,
    gmd_localisedcharacterstring text,
    gmd_localisedcharacterstring_attr_id text,
    gmd_localisedcharacterstring_attr_locale text
);
CREATE TABLE au_administrativeunit_au_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_8 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_9 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_10 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_11 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_12 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_13 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE au_administrativeunit_au_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES au_administrativeunit_au_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_14 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_15 boolean
);
CREATE TABLE au_administrativeunit_au_residenceofauthority (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_la_16 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_la_17 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_la_18 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_20 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_21 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_22 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_23 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_24 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_25 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_27 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_28 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_29 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_30 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_31 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_32 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_so_33 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_so_34 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_so_35 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_37 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_38 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_40 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_41 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_42 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_43 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_44 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_45 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_56 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_57 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_58 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_59 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_60 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_61 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_63 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_64 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_65 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_66 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_67 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_68 text,
    au_residenceofauthority_au_geometry_attr_nilreason text,
    au_residenceofauthority_au_geometry_attr_gml_remoteschema text,
    au_residenceofauthority_au_geometry_attr_owns boolean,
    au_residenceofauthority_au_geometry_attr_xsi_nil boolean
);
CREATE TABLE au_administrativeunit_au_residenceofauthority_au_residenc_46 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES au_administrativeunit_au_residenceofauthority ON DELETE CASCADE,
    num integer not null,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_48 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_49 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_50 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_51 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_52 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_53 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_54 boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'au_administrativeunit_au_residenceofauthority','au_residenceofauthority_au_geometry_value','0','GEOMETRY', 2);
CREATE TABLE au_administrativeunit_au_condominium (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit_au_lowerlevelunit (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_owns boolean,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit_au_administeredby (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit_au_coadminister (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit_au_boundary (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_condominium (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    au_inspireid_base_identifier_base_localid text,
    au_inspireid_base_identifier_base_namespace text,
    au_inspireid_base_identifier_base_versionid text,
    au_inspireid_base_identifier_base_versionid_attr_nilreason text,
    au_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    au_geometry_attr_nilreason text,
    au_geometry_attr_gml_remoteschema text,
    au_geometry_attr_owns boolean,
    au_beginlifespanversion timestamp,
    au_beginlifespanversion_attr_nilreason text,
    au_beginlifespanversion_attr_xsi_nil boolean,
    au_endlifespanversion timestamp,
    au_endlifespanversion_attr_nilreason text,
    au_endlifespanversion_attr_xsi_nil boolean,
    CONSTRAINT au_condominium_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE au_condominium_au_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_condominium ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_0 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_1 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_2 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_3 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_4 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_5 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE au_condominium_au_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES au_condominium_au_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_6 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_7 boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'au_condominium','au_geometry_value','0','GEOMETRY', 2);
CREATE TABLE au_condominium_au_admunit (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_condominium ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE cp_basicpropertyunit (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    cp_inspireid_base_identifier_base_localid text,
    cp_inspireid_base_identifier_base_namespace text,
    cp_inspireid_base_identifier_base_versionid text,
    cp_inspireid_base_identifier_base_versionid_attr_nilreason text,
    cp_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    cp_nationalcadastralreference text,
    cp_areavalue numeric,
    cp_areavalue_attr_nilreason text,
    cp_areavalue_attr_uom text,
    cp_areavalue_attr_xsi_nil boolean,
    cp_validfrom timestamp,
    cp_validfrom_attr_nilreason text,
    cp_validfrom_attr_xsi_nil boolean,
    cp_validto timestamp,
    cp_validto_attr_nilreason text,
    cp_validto_attr_xsi_nil boolean,
    cp_beginlifespanversion timestamp,
    cp_beginlifespanversion_attr_nilreason text,
    cp_beginlifespanversion_attr_xsi_nil boolean,
    cp_endlifespanversion timestamp,
    cp_endlifespanversion_attr_nilreason text,
    cp_endlifespanversion_attr_xsi_nil boolean,
    cp_administrativeunit_attr_owns boolean,
    cp_administrativeunit_attr_nilreason text,
    cp_administrativeunit_attr_gml_remoteschema text,
    cp_administrativeunit_attr_xsi_nil boolean,
    cp_administrativeunit_fk text,
    cp_administrativeunit_href text,
    CONSTRAINT cp_basicpropertyunit_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE cp_cadastralboundary (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    cp_beginlifespanversion timestamp,
    cp_beginlifespanversion_attr_nilreason text,
    cp_beginlifespanversion_attr_xsi_nil boolean,
    cp_endlifespanversion timestamp,
    cp_endlifespanversion_attr_nilreason text,
    cp_endlifespanversion_attr_xsi_nil boolean,
    cp_estimatedaccuracy numeric,
    cp_estimatedaccuracy_attr_nilreason text,
    cp_estimatedaccuracy_attr_uom text,
    cp_estimatedaccuracy_attr_xsi_nil boolean,
    cp_geometry_attr_nilreason text,
    cp_geometry_attr_gml_remoteschema text,
    cp_geometry_attr_owns boolean,
    cp_inspireid_base_identifier_base_localid text,
    cp_inspireid_base_identifier_base_namespace text,
    cp_inspireid_base_identifier_base_versionid text,
    cp_inspireid_base_identifier_base_versionid_attr_nilreason text,
    cp_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    cp_validfrom timestamp,
    cp_validfrom_attr_nilreason text,
    cp_validfrom_attr_xsi_nil boolean,
    cp_validto timestamp,
    cp_validto_attr_nilreason text,
    cp_validto_attr_xsi_nil boolean,
    CONSTRAINT cp_cadastralboundary_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'cp_cadastralboundary','cp_geometry_value','0','GEOMETRY', 2);
CREATE TABLE cp_cadastralboundary_cp_parcel (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES cp_cadastralboundary ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE cp_cadastralparcel (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    cp_areavalue numeric,
    cp_areavalue_attr_nilreason text,
    cp_areavalue_attr_uom text,
    cp_areavalue_attr_xsi_nil boolean,
    cp_beginlifespanversion timestamp,
    cp_beginlifespanversion_attr_nilreason text,
    cp_beginlifespanversion_attr_xsi_nil boolean,
    cp_endlifespanversion timestamp,
    cp_endlifespanversion_attr_nilreason text,
    cp_endlifespanversion_attr_xsi_nil boolean,
    cp_geometry_attr_nilreason text,
    cp_geometry_attr_gml_remoteschema text,
    cp_geometry_attr_owns boolean,
    cp_inspireid_base_identifier_base_localid text,
    cp_inspireid_base_identifier_base_namespace text,
    cp_inspireid_base_identifier_base_versionid text,
    cp_inspireid_base_identifier_base_versionid_attr_nilreason text,
    cp_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    cp_label text,
    cp_nationalcadastralreference text,
    cp_referencepoint_attr_nilreason text,
    cp_referencepoint_attr_gml_remoteschema text,
    cp_referencepoint_attr_owns boolean,
    cp_referencepoint_attr_xsi_nil boolean,
    cp_validfrom timestamp,
    cp_validfrom_attr_nilreason text,
    cp_validfrom_attr_xsi_nil boolean,
    cp_validto timestamp,
    cp_validto_attr_nilreason text,
    cp_validto_attr_xsi_nil boolean,
    cp_administrativeunit_attr_owns boolean,
    cp_administrativeunit_attr_nilreason text,
    cp_administrativeunit_attr_gml_remoteschema text,
    cp_administrativeunit_attr_xsi_nil boolean,
    cp_administrativeunit_fk text,
    cp_administrativeunit_href text,
    cp_zoning_attr_owns boolean,
    cp_zoning_attr_nilreason text,
    cp_zoning_attr_gml_remoteschema text,
    cp_zoning_attr_xsi_nil boolean,
    cp_zoning_fk text,
    cp_zoning_href text,
    CONSTRAINT cp_cadastralparcel_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'cp_cadastralparcel','cp_geometry_value','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'cp_cadastralparcel','cp_referencepoint_value','0','GEOMETRY', 2);
CREATE TABLE cp_cadastralparcel_cp_basicpropertyunit (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES cp_cadastralparcel ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE cp_cadastralzoning (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    cp_beginlifespanversion timestamp,
    cp_beginlifespanversion_attr_nilreason text,
    cp_beginlifespanversion_attr_xsi_nil boolean,
    cp_endlifespanversion timestamp,
    cp_endlifespanversion_attr_nilreason text,
    cp_endlifespanversion_attr_xsi_nil boolean,
    cp_estimatedaccuracy numeric,
    cp_estimatedaccuracy_attr_nilreason text,
    cp_estimatedaccuracy_attr_uom text,
    cp_estimatedaccuracy_attr_xsi_nil boolean,
    cp_geometry_attr_nilreason text,
    cp_geometry_attr_gml_remoteschema text,
    cp_geometry_attr_owns boolean,
    cp_inspireid_base_identifier_base_localid text,
    cp_inspireid_base_identifier_base_namespace text,
    cp_inspireid_base_identifier_base_versionid text,
    cp_inspireid_base_identifier_base_versionid_attr_nilreason text,
    cp_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    cp_label text,
    cp_level_attr_owns boolean,
    cp_level_attr_nilreason text,
    cp_level_attr_gml_remoteschema text,
    cp_level_attr_xsi_nil boolean,
    cp_level_fk text,
    cp_level_href text,
    cp_nationalcadastalzoningreference text,
    cp_originalmapscaledenominator integer,
    cp_originalmapscaledenominator_attr_nilreason text,
    cp_originalmapscaledenominator_attr_xsi_nil boolean,
    cp_referencepoint_attr_nilreason text,
    cp_referencepoint_attr_gml_remoteschema text,
    cp_referencepoint_attr_owns boolean,
    cp_referencepoint_attr_xsi_nil boolean,
    cp_validfrom timestamp,
    cp_validfrom_attr_nilreason text,
    cp_validfrom_attr_xsi_nil boolean,
    cp_validto timestamp,
    cp_validto_attr_nilreason text,
    cp_validto_attr_xsi_nil boolean,
    cp_upperlevelunit_attr_owns boolean,
    cp_upperlevelunit_attr_nilreason text,
    cp_upperlevelunit_attr_gml_remoteschema text,
    cp_upperlevelunit_attr_xsi_nil boolean,
    cp_upperlevelunit_fk text,
    cp_upperlevelunit_href text,
    CONSTRAINT cp_cadastralzoning_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'cp_cadastralzoning','cp_geometry_value','0','GEOMETRY', 2);
CREATE TABLE cp_cadastralzoning_cp_levelname (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES cp_cadastralzoning ON DELETE CASCADE,
    num integer not null,
    attr_xlink_type text,
    attr_xlink_href text,
    attr_xlink_role text,
    attr_xlink_arcrole text,
    attr_xlink_title text,
    attr_xlink_show text,
    attr_xlink_actuate text,
    attr_uuidref text,
    attr_gco_nilreason text,
    attr_xsi_nil boolean,
    gmd_localisedcharacterstring text,
    gmd_localisedcharacterstring_attr_id text,
    gmd_localisedcharacterstring_attr_locale text
);
CREATE TABLE cp_cadastralzoning_cp_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES cp_cadastralzoning ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_69 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_70 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_71 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_72 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_73 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_74 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE cp_cadastralzoning_cp_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES cp_cadastralzoning_cp_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_75 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_76 boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'cp_cadastralzoning','cp_referencepoint_value','0','GEOMETRY', 2);
CREATE TABLE gn_namedplace (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    gn_beginlifespanversion timestamp,
    gn_beginlifespanversion_attr_nilreason text,
    gn_beginlifespanversion_attr_xsi_nil boolean,
    gn_endlifespanversion timestamp,
    gn_endlifespanversion_attr_nilreason text,
    gn_endlifespanversion_attr_xsi_nil boolean,
    gn_geometry_attr_nilreason text,
    gn_geometry_attr_gml_remoteschema text,
    gn_geometry_attr_owns boolean,
    gn_inspireid_base_identifier_base_localid text,
    gn_inspireid_base_identifier_base_namespace text,
    gn_inspireid_base_identifier_base_versionid text,
    gn_inspireid_base_identifier_base_versionid_attr_nilreason text,
    gn_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_attr_nilreason text,
    gn_leastdetailedviewingresolution_attr_owns boolean,
    gn_leastdetailedviewingresolution_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_78 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_79 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_80 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_81 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_82 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_83 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_84 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_85 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_86 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_88 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_89 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_91 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_92 integer,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_94 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_95 numeric,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_96 text,
    gn_mostdetailedviewingresolution_attr_nilreason text,
    gn_mostdetailedviewingresolution_attr_owns boolean,
    gn_mostdetailedviewingresolution_attr_xsi_nil boolean,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_98 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_99 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_100 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_101 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_102 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_103 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_104 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_105 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_106 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_108 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_109 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_111 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_112 integer,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_114 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_115 numeric,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_116 text,
    CONSTRAINT gn_namedplace_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'gn_namedplace','gn_geometry_value','0','GEOMETRY', 2);
CREATE TABLE gn_namedplace_gn_localtype (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_xlink_type text,
    attr_xlink_href text,
    attr_xlink_role text,
    attr_xlink_arcrole text,
    attr_xlink_title text,
    attr_xlink_show text,
    attr_xlink_actuate text,
    attr_uuidref text,
    attr_gco_nilreason text,
    attr_xsi_nil boolean,
    gmd_localisedcharacterstring text,
    gmd_localisedcharacterstring_attr_id text,
    gmd_localisedcharacterstring_attr_locale text
);
CREATE TABLE gn_namedplace_gn_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_117 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_118 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_119 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_120 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_121 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_122 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE gn_namedplace_gn_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES gn_namedplace_gn_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_123 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_124 boolean
);
CREATE TABLE gn_namedplace_gn_relatedspatialobject (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    base_identifier_base_localid text,
    base_identifier_base_namespace text,
    base_identifier_base_versionid text,
    base_identifier_base_versionid_attr_nilreason text,
    base_identifier_base_versionid_attr_xsi_nil boolean
);
CREATE TABLE gn_namedplace_gn_type (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
