CREATE DATABASE deegree_inspire_au WITH OWNER=deegree TEMPLATE=postgis_template;
\c deegree_inspire_au


CREATE TABLE au_administrativeboundary (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    au_geometry_attr_nilreason text,
    au_geometry_attr_gml_remoteschema text,
    au_geometry_attr_owns boolean,
    au_inspireid_base_identifier_base_localid text,
    au_inspireid_base_identifier_base_namespace text,
    au_inspireid_base_identifier_base_versionid text,
    au_inspireid_base_identifier_base_versionid_attr_nilreason text,
    au_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    au_country_attr_gco_nilreason text,
    au_country_gmd_country text,
    au_country_gmd_country_attr_codelist text,
    au_country_gmd_country_attr_codelistvalue text,
    au_country_gmd_country_attr_codespace text,
    au_legalstatus text,
    au_legalstatus_attr_nilreason text,
    au_legalstatus_attr_xsi_nil boolean,
    au_technicalstatus text,
    au_technicalstatus_attr_nilreason text,
    au_technicalstatus_attr_xsi_nil boolean,
    au_beginlifespanversion timestamp,
    au_beginlifespanversion_attr_nilreason text,
    au_beginlifespanversion_attr_xsi_nil boolean,
    au_endlifespanversion timestamp,
    au_endlifespanversion_attr_nilreason text,
    au_endlifespanversion_attr_xsi_nil boolean,
    CONSTRAINT au_administrativeboundary_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'au_administrativeboundary','au_geometry_value','0','GEOMETRY', 2);
CREATE TABLE au_administrativeboundary_au_nationallevel (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeboundary ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    fk text,
    href text
);
CREATE TABLE au_administrativeboundary_au_admunit (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeboundary ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    au_geometry_attr_nilreason text,
    au_geometry_attr_gml_remoteschema text,
    au_geometry_attr_owns boolean,
    au_nationalcode text,
    au_inspireid_base_identifier_base_localid text,
    au_inspireid_base_identifier_base_namespace text,
    au_inspireid_base_identifier_base_versionid text,
    au_inspireid_base_identifier_base_versionid_attr_nilreason text,
    au_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    au_nationallevel_attr_owns boolean,
    au_nationallevel_attr_nilreason text,
    au_nationallevel_attr_gml_remoteschema text,
    au_nationallevel_fk text,
    au_nationallevel_href text,
    au_country_attr_gco_nilreason text,
    au_country_gmd_country text,
    au_country_gmd_country_attr_codelist text,
    au_country_gmd_country_attr_codelistvalue text,
    au_country_gmd_country_attr_codespace text,
    au_beginlifespanversion timestamp,
    au_beginlifespanversion_attr_nilreason text,
    au_beginlifespanversion_attr_xsi_nil boolean,
    au_endlifespanversion timestamp,
    au_endlifespanversion_attr_nilreason text,
    au_endlifespanversion_attr_xsi_nil boolean,
    au_upperlevelunit_attr_owns boolean,
    au_upperlevelunit_attr_nilreason text,
    au_upperlevelunit_attr_gml_remoteschema text,
    au_upperlevelunit_attr_xsi_nil boolean,
    au_upperlevelunit_fk text,
    au_upperlevelunit_href text,
    CONSTRAINT au_administrativeunit_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'au_administrativeunit','au_geometry_value','0','GEOMETRY', 2);
CREATE TABLE au_administrativeunit_au_nationallevelname (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_xlink_type text,
    attr_xlink_href text,
    attr_xlink_role text,
    attr_xlink_arcrole text,
    attr_xlink_title text,
    attr_xlink_show text,
    attr_xlink_actuate text,
    attr_uuidref text,
    attr_gco_nilreason text,
    attr_xsi_nil boolean,
    gmd_localisedcharacterstring text,
    gmd_localisedcharacterstring_attr_id text,
    gmd_localisedcharacterstring_attr_locale text
);
CREATE TABLE au_administrativeunit_au_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_0 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_1 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_2 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_3 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_4 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_5 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE au_administrativeunit_au_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES au_administrativeunit_au_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_6 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_7 boolean
);
CREATE TABLE au_administrativeunit_au_residenceofauthority (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_la_8 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_la_9 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_la_10 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_12 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_13 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_14 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_15 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_16 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_17 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_19 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_20 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_21 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_22 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_23 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_na_24 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_so_25 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_so_26 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_so_27 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_29 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_30 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_32 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_33 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_34 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_35 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_36 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_pr_37 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_48 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_49 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_50 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_51 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_52 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_53 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_55 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_56 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_57 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_58 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_59 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_gr_60 text,
    au_residenceofauthority_au_geometry_attr_nilreason text,
    au_residenceofauthority_au_geometry_attr_gml_remoteschema text,
    au_residenceofauthority_au_geometry_attr_owns boolean,
    au_residenceofauthority_au_geometry_attr_xsi_nil boolean
);
CREATE TABLE au_administrativeunit_au_residenceofauthority_au_residenc_38 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES au_administrativeunit_au_residenceofauthority ON DELETE CASCADE,
    num integer not null,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_40 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_41 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_42 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_43 boolean,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_44 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_45 text,
    au_residenceofauthority_au_name_gn_geographicalname_gn_sp_46 boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'au_administrativeunit_au_residenceofauthority','au_residenceofauthority_au_geometry_value','0','GEOMETRY', 2);
CREATE TABLE au_administrativeunit_au_condominium (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit_au_lowerlevelunit (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_owns boolean,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit_au_administeredby (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit_au_coadminister (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_administrativeunit_au_boundary (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE au_condominium (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    au_inspireid_base_identifier_base_localid text,
    au_inspireid_base_identifier_base_namespace text,
    au_inspireid_base_identifier_base_versionid text,
    au_inspireid_base_identifier_base_versionid_attr_nilreason text,
    au_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    au_geometry_attr_nilreason text,
    au_geometry_attr_gml_remoteschema text,
    au_geometry_attr_owns boolean,
    au_beginlifespanversion timestamp,
    au_beginlifespanversion_attr_nilreason text,
    au_beginlifespanversion_attr_xsi_nil boolean,
    au_endlifespanversion timestamp,
    au_endlifespanversion_attr_nilreason text,
    au_endlifespanversion_attr_xsi_nil boolean,
    CONSTRAINT au_condominium_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE au_condominium_au_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_condominium ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_61 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_62 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_63 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_64 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_65 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_66 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE au_condominium_au_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES au_condominium_au_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_67 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_68 boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'au_condominium','au_geometry_value','0','GEOMETRY', 2);
CREATE TABLE au_condominium_au_admunit (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES au_condominium ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE gn_namedplace (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    gn_beginlifespanversion timestamp,
    gn_beginlifespanversion_attr_nilreason text,
    gn_beginlifespanversion_attr_xsi_nil boolean,
    gn_endlifespanversion timestamp,
    gn_endlifespanversion_attr_nilreason text,
    gn_endlifespanversion_attr_xsi_nil boolean,
    gn_geometry_attr_nilreason text,
    gn_geometry_attr_gml_remoteschema text,
    gn_geometry_attr_owns boolean,
    gn_inspireid_base_identifier_base_localid text,
    gn_inspireid_base_identifier_base_namespace text,
    gn_inspireid_base_identifier_base_versionid text,
    gn_inspireid_base_identifier_base_versionid_attr_nilreason text,
    gn_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_attr_nilreason text,
    gn_leastdetailedviewingresolution_attr_owns boolean,
    gn_leastdetailedviewingresolution_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_70 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_71 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_72 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_73 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_74 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_75 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_76 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_77 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_78 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_80 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_81 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_83 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_84 integer,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_86 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_87 numeric,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_88 text,
    gn_mostdetailedviewingresolution_attr_nilreason text,
    gn_mostdetailedviewingresolution_attr_owns boolean,
    gn_mostdetailedviewingresolution_attr_xsi_nil boolean,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_90 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_91 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_92 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_93 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_94 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_95 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_96 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_97 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_98 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_100 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_101 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_103 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_104 integer,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_106 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_107 numeric,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_108 text,
    CONSTRAINT gn_namedplace_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'gn_namedplace','gn_geometry_value','0','GEOMETRY', 2);
CREATE TABLE gn_namedplace_gn_localtype (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_xlink_type text,
    attr_xlink_href text,
    attr_xlink_role text,
    attr_xlink_arcrole text,
    attr_xlink_title text,
    attr_xlink_show text,
    attr_xlink_actuate text,
    attr_uuidref text,
    attr_gco_nilreason text,
    attr_xsi_nil boolean,
    gmd_localisedcharacterstring text,
    gmd_localisedcharacterstring_attr_id text,
    gmd_localisedcharacterstring_attr_locale text
);
CREATE TABLE gn_namedplace_gn_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_109 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_110 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_111 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_112 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_113 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_114 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE gn_namedplace_gn_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES gn_namedplace_gn_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_115 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_116 boolean
);
CREATE TABLE gn_namedplace_gn_relatedspatialobject (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    base_identifier_base_localid text,
    base_identifier_base_namespace text,
    base_identifier_base_versionid text,
    base_identifier_base_versionid_attr_nilreason text,
    base_identifier_base_versionid_attr_xsi_nil boolean
);
CREATE TABLE gn_namedplace_gn_type (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
