CREATE DATABASE deegree_inspire_gn WITH OWNER=deegree TEMPLATE=postgis_template;
\c deegree_inspire_gn


CREATE TABLE gn_namedplace (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    gn_beginlifespanversion timestamp,
    gn_beginlifespanversion_attr_nilreason text,
    gn_beginlifespanversion_attr_xsi_nil boolean,
    gn_endlifespanversion timestamp,
    gn_endlifespanversion_attr_nilreason text,
    gn_endlifespanversion_attr_xsi_nil boolean,
    gn_geometry_attr_nilreason text,
    gn_geometry_attr_gml_remoteschema text,
    gn_geometry_attr_owns boolean,
    gn_inspireid_base_identifier_base_localid text,
    gn_inspireid_base_identifier_base_namespace text,
    gn_inspireid_base_identifier_base_versionid text,
    gn_inspireid_base_identifier_base_versionid_attr_nilreason text,
    gn_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_attr_nilreason text,
    gn_leastdetailedviewingresolution_attr_owns boolean,
    gn_leastdetailedviewingresolution_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_1 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_2 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_3 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_4 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_5 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_6 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_7 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_8 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_9 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_11 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_12 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_14 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_15 integer,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_17 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_18 numeric,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_19 text,
    gn_mostdetailedviewingresolution_attr_nilreason text,
    gn_mostdetailedviewingresolution_attr_owns boolean,
    gn_mostdetailedviewingresolution_attr_xsi_nil boolean,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_21 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_22 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_23 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_24 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_25 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_26 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_27 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_28 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_29 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_31 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_32 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_34 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_35 integer,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_37 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_38 numeric,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_39 text,
    CONSTRAINT gn_namedplace_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'gn_namedplace','gn_geometry_value','0','GEOMETRY', 2);
CREATE TABLE gn_namedplace_gn_localtype (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_xlink_type text,
    attr_xlink_href text,
    attr_xlink_role text,
    attr_xlink_arcrole text,
    attr_xlink_title text,
    attr_xlink_show text,
    attr_xlink_actuate text,
    attr_uuidref text,
    attr_gco_nilreason text,
    attr_xsi_nil boolean,
    gmd_localisedcharacterstring text,
    gmd_localisedcharacterstring_attr_id text,
    gmd_localisedcharacterstring_attr_locale text
);
CREATE TABLE gn_namedplace_gn_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_40 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_41 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_42 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_43 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_44 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_45 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE gn_namedplace_gn_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES gn_namedplace_gn_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_46 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_47 boolean
);
CREATE TABLE gn_namedplace_gn_relatedspatialobject (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    base_identifier_base_localid text,
    base_identifier_base_namespace text,
    base_identifier_base_versionid text,
    base_identifier_base_versionid_attr_nilreason text,
    base_identifier_base_versionid_attr_xsi_nil boolean
);
CREATE TABLE gn_namedplace_gn_type (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
