CREATE DATABASE deegree_inspire_bu WITH OWNER=deegree TEMPLATE=postgis_template;
\c deegree_inspire_bu


CREATE TABLE bu_core2d_building (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    bu_base_beginlifespanversion timestamp,
    bu_base_beginlifespanversion_attr_nilreason text,
    bu_base_beginlifespanversion_attr_xsi_nil boolean,
    bu_base_conditionofconstruction_attr_owns boolean,
    bu_base_conditionofconstruction_attr_nilreason text,
    bu_base_conditionofconstruction_attr_gml_remoteschema text,
    bu_base_conditionofconstruction_attr_xsi_nil boolean,
    bu_base_conditionofconstruction_fk text,
    bu_base_conditionofconstruction_href text,
    bu_base_dateofconstruction_attr_nilreason text,
    bu_base_dateofconstruction_attr_xsi_nil boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_835 timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_836 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_837 boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_838 timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_839 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_840 boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_en_841 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_en_842 boolean,
    bu_base_dateofdemolition_attr_nilreason text,
    bu_base_dateofdemolition_attr_xsi_nil boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anypoint timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anyp_843 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anyp_844 boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_beginning timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_begi_845 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_begi_846 boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end__847 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end__848 boolean,
    bu_base_dateofrenovation_attr_nilreason text,
    bu_base_dateofrenovation_attr_xsi_nil boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anypoint timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anyp_849 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anyp_850 boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_beginning timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_begi_851 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_begi_852 boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end__853 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end__854 boolean,
    bu_base_endlifespanversion timestamp,
    bu_base_endlifespanversion_attr_nilreason text,
    bu_base_endlifespanversion_attr_xsi_nil boolean,
    bu_base_inspireid_base_identifier_base_localid text,
    bu_base_inspireid_base_identifier_base_namespace text,
    bu_base_inspireid_base_identifier_base_versionid text,
    bu_base_inspireid_base_identifier_base_versionid_attr_nil_877 text,
    bu_base_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    bu_base_numberofdwellings integer,
    bu_base_numberofdwellings_attr_nilreason text,
    bu_base_numberofdwellings_attr_xsi_nil boolean,
    bu_base_numberofbuildingunits integer,
    bu_base_numberofbuildingunits_attr_nilreason text,
    bu_base_numberofbuildingunits_attr_xsi_nil boolean,
    bu_base_numberoffloorsaboveground integer,
    bu_base_numberoffloorsaboveground_attr_nilreason text,
    bu_base_numberoffloorsaboveground_attr_xsi_nil boolean,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_g_888 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_g_889 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_g_890 boolean,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_r_892 boolean,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_h_894 boolean,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_h_895 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_h_896 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_h_897 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_h_898 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_v_900 boolean,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_v_901 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_v_902 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_v_903 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_v_904 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_h_905 numeric,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_h_906 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_h_907 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_h_908 boolean,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_v_909 numeric,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_v_910 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_v_911 text,
    bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_v_912 boolean,
    CONSTRAINT bu_core2d_building_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE bu_core2d_building_bu_base_elevation (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_elevation_bu_base_elevationreference_attr_owns boolean,
    bu_base_elevation_bu_base_elevationreference_attr_nilreason text,
    bu_base_elevation_bu_base_elevationreference_attr_gml_rem_855 text,
    bu_base_elevation_bu_base_elevationreference_fk text,
    bu_base_elevation_bu_base_elevationreference_href text,
    bu_base_elevation_bu_base_elevationvalue text,
    bu_base_elevation_bu_base_elevationvalue_attr_srsname text,
    bu_base_elevation_bu_base_elevationvalue_attr_srsdimension integer,
    bu_base_elevation_bu_base_elevationvalue_attr_axislabels text,
    bu_base_elevation_bu_base_elevationvalue_attr_uomlabels text
);
CREATE TABLE bu_core2d_building_bu_base_externalreference (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_externalreference_bu_base_informationsystem text,
    bu_base_externalreference_bu_base_informationsystemname_a_856 text,
    bu_base_externalreference_bu_base_informationsystemname_g_857 text,
    bu_base_externalreference_bu_base_informationsystemname_g_859 text,
    bu_base_externalreference_bu_base_informationsystemname_g_860 text,
    bu_base_externalreference_bu_base_reference text
);
CREATE TABLE bu_core2d_building_bu_base_externalreference_bu_base_exte_861 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES bu_core2d_building_bu_base_externalreference ON DELETE CASCADE,
    num integer not null,
    bu_base_externalreference_bu_base_informationsystemname_g_862 text,
    bu_base_externalreference_bu_base_informationsystemname_g_863 text,
    bu_base_externalreference_bu_base_informationsystemname_g_864 text,
    bu_base_externalreference_bu_base_informationsystemname_g_865 text,
    bu_base_externalreference_bu_base_informationsystemname_g_866 text,
    bu_base_externalreference_bu_base_informationsystemname_g_867 text,
    bu_base_externalreference_bu_base_informationsystemname_g_868 text,
    bu_base_externalreference_bu_base_informationsystemname_g_869 text,
    bu_base_externalreference_bu_base_informationsystemname_g_870 text,
    bu_base_externalreference_bu_base_informationsystemname_g_871 text,
    bu_base_externalreference_bu_base_informationsystemname_g_872 text,
    bu_base_externalreference_bu_base_informationsystemname_g_873 text
);
CREATE TABLE bu_core2d_building_bu_base_heightaboveground (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_heightreference_attr_owns boolean,
    bu_base_heightaboveground_bu_base_heightreference_attr_ni_874 text,
    bu_base_heightaboveground_bu_base_heightreference_attr_gm_875 text,
    bu_base_heightaboveground_bu_base_heightreference_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_heightreference_fk text,
    bu_base_heightaboveground_bu_base_heightreference_href text,
    bu_base_heightaboveground_bu_base_lowreference_attr_owns boolean,
    bu_base_heightaboveground_bu_base_lowreference_attr_nilreason text,
    bu_base_heightaboveground_bu_base_lowreference_attr_gml_r_876 text,
    bu_base_heightaboveground_bu_base_lowreference_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_lowreference_fk text,
    bu_base_heightaboveground_bu_base_lowreference_href text,
    bu_base_heightaboveground_bu_base_status_attr_owns boolean,
    bu_base_heightaboveground_bu_base_status_attr_nilreason text,
    bu_base_heightaboveground_bu_base_status_attr_gml_remoteschema text,
    bu_base_heightaboveground_bu_base_status_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_status_fk text,
    bu_base_heightaboveground_bu_base_status_href text,
    bu_base_heightaboveground_bu_base_value numeric,
    bu_base_heightaboveground_bu_base_value_attr_uom text
);
CREATE TABLE bu_core2d_building_bu_base_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_878 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_879 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_880 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_881 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_882 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_883 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE bu_core2d_building_bu_base_name_gn_geographicalname_gn_sp_884 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES bu_core2d_building_bu_base_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_885 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_886 boolean
);
CREATE TABLE bu_core2d_building_bu_base_buildingnature (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_building ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE bu_core2d_building_bu_base_currentuse (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_currentuse_bu_base_currentuse_attr_owns boolean,
    bu_base_currentuse_bu_base_currentuse_attr_nilreason text,
    bu_base_currentuse_bu_base_currentuse_attr_gml_remoteschema text,
    bu_base_currentuse_bu_base_currentuse_fk text,
    bu_base_currentuse_bu_base_currentuse_href text,
    bu_base_currentuse_bu_base_percentage integer,
    bu_base_currentuse_bu_base_percentage_attr_nilreason text,
    bu_base_currentuse_bu_base_percentage_attr_xsi_nil boolean
);
CREATE TABLE bu_core2d_building_bu_base_parts (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_owns boolean,
    attr_xsi_nil boolean,
    fk text,
    href text
);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core2d_building','bu_core2d_geometry2d_bu_base_buildinggeometry2d_bu_base_g_891','0','GEOMETRY', 2);
CREATE TABLE bu_core2d_buildingpart (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    bu_base_beginlifespanversion timestamp,
    bu_base_beginlifespanversion_attr_nilreason text,
    bu_base_beginlifespanversion_attr_xsi_nil boolean,
    bu_base_conditionofconstruction_attr_owns boolean,
    bu_base_conditionofconstruction_attr_nilreason text,
    bu_base_conditionofconstruction_attr_gml_remoteschema text,
    bu_base_conditionofconstruction_attr_xsi_nil boolean,
    bu_base_conditionofconstruction_fk text,
    bu_base_conditionofconstruction_href text,
    bu_base_dateofconstruction_attr_nilreason text,
    bu_base_dateofconstruction_attr_xsi_nil boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_382 timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_383 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_384 boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_385 timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_386 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_387 boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_en_388 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_en_389 boolean,
    bu_base_dateofdemolition_attr_nilreason text,
    bu_base_dateofdemolition_attr_xsi_nil boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anypoint timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anyp_390 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anyp_391 boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_beginning timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_begi_392 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_begi_393 boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end__394 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end__395 boolean,
    bu_base_dateofrenovation_attr_nilreason text,
    bu_base_dateofrenovation_attr_xsi_nil boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anypoint timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anyp_396 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anyp_397 boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_beginning timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_begi_398 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_begi_399 boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end__400 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end__401 boolean,
    bu_base_endlifespanversion timestamp,
    bu_base_endlifespanversion_attr_nilreason text,
    bu_base_endlifespanversion_attr_xsi_nil boolean,
    bu_base_inspireid_base_identifier_base_localid text,
    bu_base_inspireid_base_identifier_base_namespace text,
    bu_base_inspireid_base_identifier_base_versionid text,
    bu_base_inspireid_base_identifier_base_versionid_attr_nil_424 text,
    bu_base_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    bu_base_numberofdwellings integer,
    bu_base_numberofdwellings_attr_nilreason text,
    bu_base_numberofdwellings_attr_xsi_nil boolean,
    bu_base_numberofbuildingunits integer,
    bu_base_numberofbuildingunits_attr_nilreason text,
    bu_base_numberofbuildingunits_attr_xsi_nil boolean,
    bu_base_numberoffloorsaboveground integer,
    bu_base_numberoffloorsaboveground_attr_nilreason text,
    bu_base_numberoffloorsaboveground_attr_xsi_nil boolean,
    CONSTRAINT bu_core2d_buildingpart_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE bu_core2d_buildingpart_bu_base_elevation (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_elevation_bu_base_elevationreference_attr_owns boolean,
    bu_base_elevation_bu_base_elevationreference_attr_nilreason text,
    bu_base_elevation_bu_base_elevationreference_attr_gml_rem_402 text,
    bu_base_elevation_bu_base_elevationreference_fk text,
    bu_base_elevation_bu_base_elevationreference_href text,
    bu_base_elevation_bu_base_elevationvalue text,
    bu_base_elevation_bu_base_elevationvalue_attr_srsname text,
    bu_base_elevation_bu_base_elevationvalue_attr_srsdimension integer,
    bu_base_elevation_bu_base_elevationvalue_attr_axislabels text,
    bu_base_elevation_bu_base_elevationvalue_attr_uomlabels text
);
CREATE TABLE bu_core2d_buildingpart_bu_base_externalreference (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_externalreference_bu_base_informationsystem text,
    bu_base_externalreference_bu_base_informationsystemname_a_403 text,
    bu_base_externalreference_bu_base_informationsystemname_g_404 text,
    bu_base_externalreference_bu_base_informationsystemname_g_406 text,
    bu_base_externalreference_bu_base_informationsystemname_g_407 text,
    bu_base_externalreference_bu_base_reference text
);
CREATE TABLE bu_core2d_buildingpart_bu_base_externalreference_bu_base__408 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES bu_core2d_buildingpart_bu_base_externalreference ON DELETE CASCADE,
    num integer not null,
    bu_base_externalreference_bu_base_informationsystemname_g_409 text,
    bu_base_externalreference_bu_base_informationsystemname_g_410 text,
    bu_base_externalreference_bu_base_informationsystemname_g_411 text,
    bu_base_externalreference_bu_base_informationsystemname_g_412 text,
    bu_base_externalreference_bu_base_informationsystemname_g_413 text,
    bu_base_externalreference_bu_base_informationsystemname_g_414 text,
    bu_base_externalreference_bu_base_informationsystemname_g_415 text,
    bu_base_externalreference_bu_base_informationsystemname_g_416 text,
    bu_base_externalreference_bu_base_informationsystemname_g_417 text,
    bu_base_externalreference_bu_base_informationsystemname_g_418 text,
    bu_base_externalreference_bu_base_informationsystemname_g_419 text,
    bu_base_externalreference_bu_base_informationsystemname_g_420 text
);
CREATE TABLE bu_core2d_buildingpart_bu_base_heightaboveground (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_heightreference_attr_owns boolean,
    bu_base_heightaboveground_bu_base_heightreference_attr_ni_421 text,
    bu_base_heightaboveground_bu_base_heightreference_attr_gm_422 text,
    bu_base_heightaboveground_bu_base_heightreference_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_heightreference_fk text,
    bu_base_heightaboveground_bu_base_heightreference_href text,
    bu_base_heightaboveground_bu_base_lowreference_attr_owns boolean,
    bu_base_heightaboveground_bu_base_lowreference_attr_nilreason text,
    bu_base_heightaboveground_bu_base_lowreference_attr_gml_r_423 text,
    bu_base_heightaboveground_bu_base_lowreference_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_lowreference_fk text,
    bu_base_heightaboveground_bu_base_lowreference_href text,
    bu_base_heightaboveground_bu_base_status_attr_owns boolean,
    bu_base_heightaboveground_bu_base_status_attr_nilreason text,
    bu_base_heightaboveground_bu_base_status_attr_gml_remoteschema text,
    bu_base_heightaboveground_bu_base_status_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_status_fk text,
    bu_base_heightaboveground_bu_base_status_href text,
    bu_base_heightaboveground_bu_base_value numeric,
    bu_base_heightaboveground_bu_base_value_attr_uom text
);
CREATE TABLE bu_core2d_buildingpart_bu_base_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_425 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_426 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_427 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_428 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_429 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_430 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE bu_core2d_buildingpart_bu_base_name_gn_geographicalname_g_431 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES bu_core2d_buildingpart_bu_base_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_432 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_433 boolean
);
CREATE TABLE bu_core2d_buildingpart_bu_base_buildingnature (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE bu_core2d_buildingpart_bu_base_currentuse (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_currentuse_bu_base_currentuse_attr_owns boolean,
    bu_base_currentuse_bu_base_currentuse_attr_nilreason text,
    bu_base_currentuse_bu_base_currentuse_attr_gml_remoteschema text,
    bu_base_currentuse_bu_base_currentuse_fk text,
    bu_base_currentuse_bu_base_currentuse_href text,
    bu_base_currentuse_bu_base_percentage integer,
    bu_base_currentuse_bu_base_percentage_attr_nilreason text,
    bu_base_currentuse_bu_base_percentage_attr_xsi_nil boolean
);
CREATE TABLE bu_core2d_buildingpart_bu_core2d_geometry2d (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core2d_buildingpart ON DELETE CASCADE,
    num integer not null,
    bu_base_buildinggeometry2d_bu_base_geometry_attr_nilreason text,
    bu_base_buildinggeometry2d_bu_base_geometry_attr_gml_remo_434 text,
    bu_base_buildinggeometry2d_bu_base_geometry_attr_owns boolean,
    bu_base_buildinggeometry2d_bu_base_referencegeometry boolean,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_435 boolean,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_436 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_437 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_438 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_439 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_440 boolean,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_441 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_442 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_443 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_444 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_445 numeric,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_446 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_447 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_448 boolean,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_449 numeric,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_450 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_451 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_452 boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core2d_buildingpart_bu_core2d_geometry2d','bu_base_buildinggeometry2d_bu_base_geometry_value','0','GEOMETRY', 2);
CREATE TABLE bu_core3d_building (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    bu_base_beginlifespanversion timestamp,
    bu_base_beginlifespanversion_attr_nilreason text,
    bu_base_beginlifespanversion_attr_xsi_nil boolean,
    bu_base_conditionofconstruction_attr_owns boolean,
    bu_base_conditionofconstruction_attr_nilreason text,
    bu_base_conditionofconstruction_attr_gml_remoteschema text,
    bu_base_conditionofconstruction_attr_xsi_nil boolean,
    bu_base_conditionofconstruction_fk text,
    bu_base_conditionofconstruction_href text,
    bu_base_dateofconstruction_attr_nilreason text,
    bu_base_dateofconstruction_attr_xsi_nil boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_453 timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_454 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_455 boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_456 timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_457 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_458 boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_en_459 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_en_460 boolean,
    bu_base_dateofdemolition_attr_nilreason text,
    bu_base_dateofdemolition_attr_xsi_nil boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anypoint timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anyp_461 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anyp_462 boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_beginning timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_begi_463 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_begi_464 boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end__465 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end__466 boolean,
    bu_base_dateofrenovation_attr_nilreason text,
    bu_base_dateofrenovation_attr_xsi_nil boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anypoint timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anyp_467 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anyp_468 boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_beginning timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_begi_469 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_begi_470 boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end__471 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end__472 boolean,
    bu_base_endlifespanversion timestamp,
    bu_base_endlifespanversion_attr_nilreason text,
    bu_base_endlifespanversion_attr_xsi_nil boolean,
    bu_base_inspireid_base_identifier_base_localid text,
    bu_base_inspireid_base_identifier_base_namespace text,
    bu_base_inspireid_base_identifier_base_versionid text,
    bu_base_inspireid_base_identifier_base_versionid_attr_nil_495 text,
    bu_base_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    bu_base_numberofdwellings integer,
    bu_base_numberofdwellings_attr_nilreason text,
    bu_base_numberofdwellings_attr_xsi_nil boolean,
    bu_base_numberofbuildingunits integer,
    bu_base_numberofbuildingunits_attr_nilreason text,
    bu_base_numberofbuildingunits_attr_xsi_nil boolean,
    bu_base_numberoffloorsaboveground integer,
    bu_base_numberoffloorsaboveground_attr_nilreason text,
    bu_base_numberoffloorsaboveground_attr_xsi_nil boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_525 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_526 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_527 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_530 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_531 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_532 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_535 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_536 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_537 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_538 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_541 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_542 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_543 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_544 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_545 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_546 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_547 numeric,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_548 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_549 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_550 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_551 numeric,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_552 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_553 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_554 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_556 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_557 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_558 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_559 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_560 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_561 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_563 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_564 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_565 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_566 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_567 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_568 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_570 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_571 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_572 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_575 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_576 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_577 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_580 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_581 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_582 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_583 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_586 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_587 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_588 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_589 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_590 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_591 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_592 numeric,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_593 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_594 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_595 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_596 numeric,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_597 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_598 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_599 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_601 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_602 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_603 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_604 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_605 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_606 text,
    CONSTRAINT bu_core3d_building_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE bu_core3d_building_bu_base_elevation (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_elevation_bu_base_elevationreference_attr_owns boolean,
    bu_base_elevation_bu_base_elevationreference_attr_nilreason text,
    bu_base_elevation_bu_base_elevationreference_attr_gml_rem_473 text,
    bu_base_elevation_bu_base_elevationreference_fk text,
    bu_base_elevation_bu_base_elevationreference_href text,
    bu_base_elevation_bu_base_elevationvalue text,
    bu_base_elevation_bu_base_elevationvalue_attr_srsname text,
    bu_base_elevation_bu_base_elevationvalue_attr_srsdimension integer,
    bu_base_elevation_bu_base_elevationvalue_attr_axislabels text,
    bu_base_elevation_bu_base_elevationvalue_attr_uomlabels text
);
CREATE TABLE bu_core3d_building_bu_base_externalreference (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_externalreference_bu_base_informationsystem text,
    bu_base_externalreference_bu_base_informationsystemname_a_474 text,
    bu_base_externalreference_bu_base_informationsystemname_g_475 text,
    bu_base_externalreference_bu_base_informationsystemname_g_477 text,
    bu_base_externalreference_bu_base_informationsystemname_g_478 text,
    bu_base_externalreference_bu_base_reference text
);
CREATE TABLE bu_core3d_building_bu_base_externalreference_bu_base_exte_479 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES bu_core3d_building_bu_base_externalreference ON DELETE CASCADE,
    num integer not null,
    bu_base_externalreference_bu_base_informationsystemname_g_480 text,
    bu_base_externalreference_bu_base_informationsystemname_g_481 text,
    bu_base_externalreference_bu_base_informationsystemname_g_482 text,
    bu_base_externalreference_bu_base_informationsystemname_g_483 text,
    bu_base_externalreference_bu_base_informationsystemname_g_484 text,
    bu_base_externalreference_bu_base_informationsystemname_g_485 text,
    bu_base_externalreference_bu_base_informationsystemname_g_486 text,
    bu_base_externalreference_bu_base_informationsystemname_g_487 text,
    bu_base_externalreference_bu_base_informationsystemname_g_488 text,
    bu_base_externalreference_bu_base_informationsystemname_g_489 text,
    bu_base_externalreference_bu_base_informationsystemname_g_490 text,
    bu_base_externalreference_bu_base_informationsystemname_g_491 text
);
CREATE TABLE bu_core3d_building_bu_base_heightaboveground (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_heightreference_attr_owns boolean,
    bu_base_heightaboveground_bu_base_heightreference_attr_ni_492 text,
    bu_base_heightaboveground_bu_base_heightreference_attr_gm_493 text,
    bu_base_heightaboveground_bu_base_heightreference_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_heightreference_fk text,
    bu_base_heightaboveground_bu_base_heightreference_href text,
    bu_base_heightaboveground_bu_base_lowreference_attr_owns boolean,
    bu_base_heightaboveground_bu_base_lowreference_attr_nilreason text,
    bu_base_heightaboveground_bu_base_lowreference_attr_gml_r_494 text,
    bu_base_heightaboveground_bu_base_lowreference_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_lowreference_fk text,
    bu_base_heightaboveground_bu_base_lowreference_href text,
    bu_base_heightaboveground_bu_base_status_attr_owns boolean,
    bu_base_heightaboveground_bu_base_status_attr_nilreason text,
    bu_base_heightaboveground_bu_base_status_attr_gml_remoteschema text,
    bu_base_heightaboveground_bu_base_status_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_status_fk text,
    bu_base_heightaboveground_bu_base_status_href text,
    bu_base_heightaboveground_bu_base_value numeric,
    bu_base_heightaboveground_bu_base_value_attr_uom text
);
CREATE TABLE bu_core3d_building_bu_base_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_496 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_497 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_498 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_499 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_500 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_501 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE bu_core3d_building_bu_base_name_gn_geographicalname_gn_sp_502 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES bu_core3d_building_bu_base_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_503 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_504 boolean
);
CREATE TABLE bu_core3d_building_bu_base_buildingnature (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_building ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE bu_core3d_building_bu_base_currentuse (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_currentuse_bu_base_currentuse_attr_owns boolean,
    bu_base_currentuse_bu_base_currentuse_attr_nilreason text,
    bu_base_currentuse_bu_base_currentuse_attr_gml_remoteschema text,
    bu_base_currentuse_bu_base_currentuse_fk text,
    bu_base_currentuse_bu_base_currentuse_href text,
    bu_base_currentuse_bu_base_percentage integer,
    bu_base_currentuse_bu_base_percentage_attr_nilreason text,
    bu_base_currentuse_bu_base_percentage_attr_xsi_nil boolean
);
CREATE TABLE bu_core3d_building_bu_base_parts (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_owns boolean,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE bu_core3d_building_bu_core3d_geometry2d (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_building ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_buildinggeometry2d_bu_base_geometry_attr_nilreason text,
    bu_base_buildinggeometry2d_bu_base_geometry_attr_gml_remo_505 text,
    bu_base_buildinggeometry2d_bu_base_geometry_attr_owns boolean,
    bu_base_buildinggeometry2d_bu_base_referencegeometry boolean,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_506 boolean,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_507 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_508 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_509 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_510 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_511 boolean,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_512 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_513 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_514 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_515 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_516 numeric,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_517 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_518 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_519 boolean,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_520 numeric,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_521 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_522 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_523 boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_building_bu_core3d_geometry2d','bu_base_buildinggeometry2d_bu_base_geometry_value','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_building','bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_528','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_building','bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_533','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_building','bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_539','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_building','bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_573','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_building','bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_578','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_building','bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_584','0','GEOMETRY', 2);
CREATE TABLE bu_core3d_buildingpart (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    bu_base_beginlifespanversion timestamp,
    bu_base_beginlifespanversion_attr_nilreason text,
    bu_base_beginlifespanversion_attr_xsi_nil boolean,
    bu_base_conditionofconstruction_attr_owns boolean,
    bu_base_conditionofconstruction_attr_nilreason text,
    bu_base_conditionofconstruction_attr_gml_remoteschema text,
    bu_base_conditionofconstruction_attr_xsi_nil boolean,
    bu_base_conditionofconstruction_fk text,
    bu_base_conditionofconstruction_href text,
    bu_base_dateofconstruction_attr_nilreason text,
    bu_base_dateofconstruction_attr_xsi_nil boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_0 timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_1 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_an_2 boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_3 timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_4 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_be_5 boolean,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_en_6 text,
    bu_base_dateofconstruction_bu_base_dateofevent_bu_base_en_7 boolean,
    bu_base_dateofdemolition_attr_nilreason text,
    bu_base_dateofdemolition_attr_xsi_nil boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anypoint timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anyp_8 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_anyp_9 boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_beginning timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_begi_10 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_begi_11 boolean,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end__12 text,
    bu_base_dateofdemolition_bu_base_dateofevent_bu_base_end__13 boolean,
    bu_base_dateofrenovation_attr_nilreason text,
    bu_base_dateofrenovation_attr_xsi_nil boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anypoint timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anyp_14 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_anyp_15 boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_beginning timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_begi_16 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_begi_17 boolean,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end timestamp,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end__18 text,
    bu_base_dateofrenovation_bu_base_dateofevent_bu_base_end__19 boolean,
    bu_base_endlifespanversion timestamp,
    bu_base_endlifespanversion_attr_nilreason text,
    bu_base_endlifespanversion_attr_xsi_nil boolean,
    bu_base_inspireid_base_identifier_base_localid text,
    bu_base_inspireid_base_identifier_base_namespace text,
    bu_base_inspireid_base_identifier_base_versionid text,
    bu_base_inspireid_base_identifier_base_versionid_attr_nil_42 text,
    bu_base_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    bu_base_numberofdwellings integer,
    bu_base_numberofdwellings_attr_nilreason text,
    bu_base_numberofdwellings_attr_xsi_nil boolean,
    bu_base_numberofbuildingunits integer,
    bu_base_numberofbuildingunits_attr_nilreason text,
    bu_base_numberofbuildingunits_attr_xsi_nil boolean,
    bu_base_numberoffloorsaboveground integer,
    bu_base_numberoffloorsaboveground_attr_nilreason text,
    bu_base_numberoffloorsaboveground_attr_xsi_nil boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_72 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_73 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_74 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_77 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_78 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_79 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_82 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_83 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_84 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_85 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_88 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_89 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_90 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_91 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_92 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_93 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_94 numeric,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_95 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_96 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_97 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_98 numeric,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_99 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_100 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_101 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_103 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_104 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_105 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_106 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_107 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_108 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_110 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_111 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_112 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_113 boolean,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_114 text,
    bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_115 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_117 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_118 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_119 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_122 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_123 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_124 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_127 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_128 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_129 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_130 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_133 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_134 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_135 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_136 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_137 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_138 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_139 numeric,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_140 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_141 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_142 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_143 numeric,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_144 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_145 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_146 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_148 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_149 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_150 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_151 boolean,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_152 text,
    bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_153 text,
    CONSTRAINT bu_core3d_buildingpart_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE bu_core3d_buildingpart_bu_base_elevation (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_elevation_bu_base_elevationreference_attr_owns boolean,
    bu_base_elevation_bu_base_elevationreference_attr_nilreason text,
    bu_base_elevation_bu_base_elevationreference_attr_gml_rem_20 text,
    bu_base_elevation_bu_base_elevationreference_fk text,
    bu_base_elevation_bu_base_elevationreference_href text,
    bu_base_elevation_bu_base_elevationvalue text,
    bu_base_elevation_bu_base_elevationvalue_attr_srsname text,
    bu_base_elevation_bu_base_elevationvalue_attr_srsdimension integer,
    bu_base_elevation_bu_base_elevationvalue_attr_axislabels text,
    bu_base_elevation_bu_base_elevationvalue_attr_uomlabels text
);
CREATE TABLE bu_core3d_buildingpart_bu_base_externalreference (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_externalreference_bu_base_informationsystem text,
    bu_base_externalreference_bu_base_informationsystemname_a_21 text,
    bu_base_externalreference_bu_base_informationsystemname_g_22 text,
    bu_base_externalreference_bu_base_informationsystemname_g_24 text,
    bu_base_externalreference_bu_base_informationsystemname_g_25 text,
    bu_base_externalreference_bu_base_reference text
);
CREATE TABLE bu_core3d_buildingpart_bu_base_externalreference_bu_base__26 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES bu_core3d_buildingpart_bu_base_externalreference ON DELETE CASCADE,
    num integer not null,
    bu_base_externalreference_bu_base_informationsystemname_g_27 text,
    bu_base_externalreference_bu_base_informationsystemname_g_28 text,
    bu_base_externalreference_bu_base_informationsystemname_g_29 text,
    bu_base_externalreference_bu_base_informationsystemname_g_30 text,
    bu_base_externalreference_bu_base_informationsystemname_g_31 text,
    bu_base_externalreference_bu_base_informationsystemname_g_32 text,
    bu_base_externalreference_bu_base_informationsystemname_g_33 text,
    bu_base_externalreference_bu_base_informationsystemname_g_34 text,
    bu_base_externalreference_bu_base_informationsystemname_g_35 text,
    bu_base_externalreference_bu_base_informationsystemname_g_36 text,
    bu_base_externalreference_bu_base_informationsystemname_g_37 text,
    bu_base_externalreference_bu_base_informationsystemname_g_38 text
);
CREATE TABLE bu_core3d_buildingpart_bu_base_heightaboveground (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_heightreference_attr_owns boolean,
    bu_base_heightaboveground_bu_base_heightreference_attr_ni_39 text,
    bu_base_heightaboveground_bu_base_heightreference_attr_gm_40 text,
    bu_base_heightaboveground_bu_base_heightreference_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_heightreference_fk text,
    bu_base_heightaboveground_bu_base_heightreference_href text,
    bu_base_heightaboveground_bu_base_lowreference_attr_owns boolean,
    bu_base_heightaboveground_bu_base_lowreference_attr_nilreason text,
    bu_base_heightaboveground_bu_base_lowreference_attr_gml_r_41 text,
    bu_base_heightaboveground_bu_base_lowreference_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_lowreference_fk text,
    bu_base_heightaboveground_bu_base_lowreference_href text,
    bu_base_heightaboveground_bu_base_status_attr_owns boolean,
    bu_base_heightaboveground_bu_base_status_attr_nilreason text,
    bu_base_heightaboveground_bu_base_status_attr_gml_remoteschema text,
    bu_base_heightaboveground_bu_base_status_attr_xsi_nil boolean,
    bu_base_heightaboveground_bu_base_status_fk text,
    bu_base_heightaboveground_bu_base_status_href text,
    bu_base_heightaboveground_bu_base_value numeric,
    bu_base_heightaboveground_bu_base_value_attr_uom text
);
CREATE TABLE bu_core3d_buildingpart_bu_base_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_43 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_44 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_45 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_46 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_47 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_48 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE bu_core3d_buildingpart_bu_base_name_gn_geographicalname_g_49 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES bu_core3d_buildingpart_bu_base_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_50 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_51 boolean
);
CREATE TABLE bu_core3d_buildingpart_bu_base_buildingnature (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE bu_core3d_buildingpart_bu_base_currentuse (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_currentuse_bu_base_currentuse_attr_owns boolean,
    bu_base_currentuse_bu_base_currentuse_attr_nilreason text,
    bu_base_currentuse_bu_base_currentuse_attr_gml_remoteschema text,
    bu_base_currentuse_bu_base_currentuse_fk text,
    bu_base_currentuse_bu_base_currentuse_href text,
    bu_base_currentuse_bu_base_percentage integer,
    bu_base_currentuse_bu_base_percentage_attr_nilreason text,
    bu_base_currentuse_bu_base_percentage_attr_xsi_nil boolean
);
CREATE TABLE bu_core3d_buildingpart_bu_core3d_geometry2d (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES bu_core3d_buildingpart ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    bu_base_buildinggeometry2d_bu_base_geometry_attr_nilreason text,
    bu_base_buildinggeometry2d_bu_base_geometry_attr_gml_remo_52 text,
    bu_base_buildinggeometry2d_bu_base_geometry_attr_owns boolean,
    bu_base_buildinggeometry2d_bu_base_referencegeometry boolean,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_53 boolean,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_54 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_55 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_56 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryrefe_57 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_58 boolean,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_59 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_60 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_61 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryrefere_62 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_63 numeric,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_64 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_65 text,
    bu_base_buildinggeometry2d_bu_base_horizontalgeometryesti_66 boolean,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_67 numeric,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_68 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_69 text,
    bu_base_buildinggeometry2d_bu_base_verticalgeometryestima_70 boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_buildingpart_bu_core3d_geometry2d','bu_base_buildinggeometry2d_bu_base_geometry_value','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_buildingpart','bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_75','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_buildingpart','bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_80','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_buildingpart','bu_core3d_geometry3dlod1_bu_core3d_buildinggeometry3dlod1_86','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_buildingpart','bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_120','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_buildingpart','bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_125','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'bu_core3d_buildingpart','bu_core3d_geometry3dlod2_bu_core3d_buildinggeometry3dlod2_131','0','GEOMETRY', 2);
CREATE TABLE gn_namedplace (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    gn_beginlifespanversion timestamp,
    gn_beginlifespanversion_attr_nilreason text,
    gn_beginlifespanversion_attr_xsi_nil boolean,
    gn_endlifespanversion timestamp,
    gn_endlifespanversion_attr_nilreason text,
    gn_endlifespanversion_attr_xsi_nil boolean,
    gn_geometry_attr_nilreason text,
    gn_geometry_attr_gml_remoteschema text,
    gn_geometry_attr_owns boolean,
    gn_inspireid_base_identifier_base_localid text,
    gn_inspireid_base_identifier_base_namespace text,
    gn_inspireid_base_identifier_base_versionid text,
    gn_inspireid_base_identifier_base_versionid_attr_nilreason text,
    gn_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_attr_nilreason text,
    gn_leastdetailedviewingresolution_attr_owns boolean,
    gn_leastdetailedviewingresolution_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_914 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_915 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_916 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_917 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_918 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_919 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_920 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_921 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_922 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_924 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_925 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_927 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_e_928 integer,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_930 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_931 numeric,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_d_932 text,
    gn_mostdetailedviewingresolution_attr_nilreason text,
    gn_mostdetailedviewingresolution_attr_owns boolean,
    gn_mostdetailedviewingresolution_attr_xsi_nil boolean,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_934 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_935 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_936 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_937 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_938 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_939 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_940 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_941 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_942 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_944 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_945 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_947 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_eq_948 integer,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_950 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_951 numeric,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_di_952 text,
    CONSTRAINT gn_namedplace_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'gn_namedplace','gn_geometry_value','0','GEOMETRY', 2);
CREATE TABLE gn_namedplace_gn_localtype (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_xlink_type text,
    attr_xlink_href text,
    attr_xlink_role text,
    attr_xlink_arcrole text,
    attr_xlink_title text,
    attr_xlink_show text,
    attr_xlink_actuate text,
    attr_uuidref text,
    attr_gco_nilreason text,
    attr_xsi_nil boolean,
    gmd_localisedcharacterstring text,
    gmd_localisedcharacterstring_attr_id text,
    gmd_localisedcharacterstring_attr_locale text
);
CREATE TABLE gn_namedplace_gn_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_953 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_954 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_955 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_956 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_957 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofna_958 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE gn_namedplace_gn_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES gn_namedplace_gn_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_959 text,
    gn_geographicalname_gn_spellingofname_gn_transliterations_960 boolean
);
CREATE TABLE gn_namedplace_gn_relatedspatialobject (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    base_identifier_base_localid text,
    base_identifier_base_namespace text,
    base_identifier_base_versionid text,
    base_identifier_base_versionid_attr_nilreason text,
    base_identifier_base_versionid_attr_xsi_nil boolean
);
CREATE TABLE gn_namedplace_gn_type (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
