CREATE DATABASE deegree_inspire_hh WITH OWNER=deegree TEMPLATE=postgis_template;
\c deegree_inspire_hh


CREATE TABLE hh_biomarker (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    hh_aggregationunit_attr_nilreason text,
    hh_aggregationunit_attr_gml_remoteschema text,
    hh_aggregationunit_attr_owns boolean,
    hh_aggregationunit_fk text,
    hh_aggregationunit_href text,
    hh_biomarkername_hh_biomarkertype_hh_chemical_attr_owns boolean,
    hh_biomarkername_hh_biomarkertype_hh_chemical_attr_nilreason text,
    hh_biomarkername_hh_biomarkertype_hh_chemical_attr_gml_re_9 text,
    hh_biomarkername_hh_biomarkertype_hh_chemical_fk text,
    hh_biomarkername_hh_biomarkertype_hh_chemical_href text,
    hh_biomarkername_hh_biomarkertype_hh_matrix_attr_owns boolean,
    hh_biomarkername_hh_biomarkertype_hh_matrix_attr_nilreason text,
    hh_biomarkername_hh_biomarkertype_hh_matrix_attr_gml_remo_10 text,
    hh_biomarkername_hh_biomarkertype_hh_matrix_fk text,
    hh_biomarkername_hh_biomarkertype_hh_matrix_href text,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_12 numeric,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_13 text,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_14 numeric,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_15 text,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_16 numeric,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_17 text,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_18 numeric,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_19 text,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_20 numeric,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_21 text,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_22 numeric,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_23 text,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_24 numeric,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_25 text,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_26 integer,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_27 numeric,
    hh_biomarkerstatisticalparameter_hh_biomarkerstatisticalp_28 numeric,
    hh_referenceperiod_hh_referenceperiodtype_hh_startdate date,
    hh_referenceperiod_hh_referenceperiodtype_hh_enddate date,
    hh_agerange_hh_agerangetype_hh_startage_hh_age_hh_month integer,
    hh_agerange_hh_agerangetype_hh_startage_hh_age_hh_week integer,
    hh_agerange_hh_agerangetype_hh_startage_hh_age_hh_year integer,
    hh_agerange_hh_agerangetype_hh_range_hh_age_hh_month integer,
    hh_agerange_hh_agerangetype_hh_range_hh_age_hh_week integer,
    hh_agerange_hh_agerangetype_hh_range_hh_age_hh_year integer,
    hh_gender_attr_owns boolean,
    hh_gender_attr_nilreason text,
    hh_gender_attr_gml_remoteschema text,
    hh_gender_fk text,
    hh_gender_href text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_att_29 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gco_30 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_32 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_33 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_attr_47 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gco__48 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__50 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__51 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_66 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_67 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_69 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_70 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_meanage_hh_ag_84 integer,
    hh_refersto_hh_biomarkerthematicmetadata_hh_meanage_hh_ag_85 integer,
    hh_refersto_hh_biomarkerthematicmetadata_hh_meanage_hh_ag_86 integer,
    hh_refersto_hh_biomarkerthematicmetadata_hh_describedby_a_87 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_describedby_a_88 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_describedby_a_89 boolean,
    hh_refersto_hh_biomarkerthematicmetadata_hh_describedby_fk text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_describedby_href text,
    CONSTRAINT hh_biomarker_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE hh_biomarker_hh_refersto_hh_biomarkerthematicmetadata_hh__34 (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES hh_biomarker ON DELETE CASCADE,
    num integer not null,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_35 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_36 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_37 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_38 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_39 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_40 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_41 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_42 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_43 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_44 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_45 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_studytype_gmd_46 text
);
CREATE TABLE hh_biomarker_hh_refersto_hh_biomarkerthematicmetadata_hh__52 (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES hh_biomarker ON DELETE CASCADE,
    num integer not null,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__53 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__54 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__55 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__56 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__57 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__58 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__59 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__60 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__61 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__62 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__63 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_areatype_gmd__64 text
);
CREATE TABLE hh_biomarker_hh_refersto_hh_biomarkerthematicmetadata_hh__71 (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES hh_biomarker ON DELETE CASCADE,
    num integer not null,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_72 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_73 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_74 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_75 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_76 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_77 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_78 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_79 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_80 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_81 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_82 text,
    hh_refersto_hh_biomarkerthematicmetadata_hh_specificsubpo_83 text
);
CREATE TABLE hh_disease (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    hh_aggregationunit_attr_nilreason text,
    hh_aggregationunit_attr_gml_remoteschema text,
    hh_aggregationunit_attr_owns boolean,
    hh_aggregationunit_fk text,
    hh_aggregationunit_href text,
    hh_agerange_attr_nilreason text,
    hh_agerange_attr_xsi_nil boolean,
    hh_agerange_hh_agerangetype_hh_startage_hh_age_hh_month integer,
    hh_agerange_hh_agerangetype_hh_startage_hh_age_hh_week integer,
    hh_agerange_hh_agerangetype_hh_startage_hh_age_hh_year integer,
    hh_agerange_hh_agerangetype_hh_range_hh_age_hh_month integer,
    hh_agerange_hh_agerangetype_hh_range_hh_age_hh_week integer,
    hh_agerange_hh_agerangetype_hh_range_hh_age_hh_year integer,
    hh_gender_attr_owns boolean,
    hh_gender_attr_nilreason text,
    hh_gender_attr_gml_remoteschema text,
    hh_gender_attr_xsi_nil boolean,
    hh_gender_fk text,
    hh_gender_href text,
    hh_referenceperiod_hh_referenceperiodtype_hh_startdate date,
    hh_referenceperiod_hh_referenceperiodtype_hh_enddate date,
    hh_pathology_attr_owns boolean,
    hh_pathology_attr_nilreason text,
    hh_pathology_attr_gml_remoteschema text,
    hh_pathology_fk text,
    hh_pathology_href text,
    hh_cod_attr_owns boolean,
    hh_cod_attr_nilreason text,
    hh_cod_attr_gml_remoteschema text,
    hh_cod_fk text,
    hh_cod_href text,
    CONSTRAINT hh_disease_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE hh_disease_hh_diseasemeasure (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES hh_disease ON DELETE CASCADE,
    num integer not null,
    hh_diseasemeasure_hh_diseasemeasuretype_attr_owns boolean,
    hh_diseasemeasure_hh_diseasemeasuretype_attr_nilreason text,
    hh_diseasemeasure_hh_diseasemeasuretype_attr_gml_remoteschema text,
    hh_diseasemeasure_hh_diseasemeasuretype_fk text,
    hh_diseasemeasure_hh_diseasemeasuretype_href text,
    hh_diseasemeasure_hh_value numeric
);
CREATE TABLE hh_envhealthdeterminantmeasure (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    hh_location_attr_nilreason text,
    hh_location_attr_gml_remoteschema text,
    hh_location_attr_owns boolean,
    hh_type_attr_owns boolean,
    hh_type_attr_nilreason text,
    hh_type_attr_gml_remoteschema text,
    hh_type_fk text,
    hh_type_href text,
    hh_beginlifespanversion timestamp,
    hh_beginlifespanversion_attr_nilreason text,
    hh_beginlifespanversion_attr_xsi_nil boolean,
    hh_endlifespanversion timestamp,
    hh_endlifespanversion_attr_nilreason text,
    hh_endlifespanversion_attr_xsi_nil boolean,
    hh_validfrom timestamp,
    hh_validfrom_attr_nilreason text,
    hh_validfrom_attr_xsi_nil boolean,
    hh_validto timestamp,
    hh_validto_attr_nilreason text,
    hh_validto_attr_xsi_nil boolean,
    hh_measure numeric,
    hh_measure_attr_uom text,
    CONSTRAINT hh_envhealthdeterminantmeasure_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'hh_envhealthdeterminantmeasure','hh_location_value','0','GEOMETRY', 2);
CREATE TABLE hh_envhealthdeterminantstatisticaldata (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    hh_aggregationunit_attr_nilreason text,
    hh_aggregationunit_attr_gml_remoteschema text,
    hh_aggregationunit_attr_owns boolean,
    hh_aggregationunit_fk text,
    hh_aggregationunit_href text,
    hh_statisticalmethod_attr_owns boolean,
    hh_statisticalmethod_attr_nilreason text,
    hh_statisticalmethod_attr_gml_remoteschema text,
    hh_statisticalmethod_fk text,
    hh_statisticalmethod_href text,
    hh_type_attr_owns boolean,
    hh_type_attr_nilreason text,
    hh_type_attr_gml_remoteschema text,
    hh_type_fk text,
    hh_type_href text,
    hh_measure numeric,
    hh_measure_attr_uom text,
    CONSTRAINT hh_envhealthdeterminantstatisticaldata_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE hh_generalhealthstatistics (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    hh_aggregationunit_attr_nilreason text,
    hh_aggregationunit_attr_gml_remoteschema text,
    hh_aggregationunit_attr_owns boolean,
    hh_aggregationunit_fk text,
    hh_aggregationunit_href text,
    hh_agerange_attr_nilreason text,
    hh_agerange_attr_xsi_nil boolean,
    hh_agerange_hh_agerangetype_hh_startage_hh_age_hh_month integer,
    hh_agerange_hh_agerangetype_hh_startage_hh_age_hh_week integer,
    hh_agerange_hh_agerangetype_hh_startage_hh_age_hh_year integer,
    hh_agerange_hh_agerangetype_hh_range_hh_age_hh_month integer,
    hh_agerange_hh_agerangetype_hh_range_hh_age_hh_week integer,
    hh_agerange_hh_agerangetype_hh_range_hh_age_hh_year integer,
    hh_gender_attr_owns boolean,
    hh_gender_attr_nilreason text,
    hh_gender_attr_gml_remoteschema text,
    hh_gender_attr_xsi_nil boolean,
    hh_gender_fk text,
    hh_gender_href text,
    hh_generalhealthname_attr_owns boolean,
    hh_generalhealthname_attr_nilreason text,
    hh_generalhealthname_attr_gml_remoteschema text,
    hh_generalhealthname_fk text,
    hh_generalhealthname_href text,
    hh_generalhealthvalue numeric,
    hh_referenceperiod_hh_referenceperiodtype_hh_startdate date,
    hh_referenceperiod_hh_referenceperiodtype_hh_enddate date,
    CONSTRAINT hh_generalhealthstatistics_pkey PRIMARY KEY (attr_gml_id)
);
CREATE TABLE hh_healthservicesstatistic (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    hh_aggregationunit_attr_nilreason text,
    hh_aggregationunit_attr_gml_remoteschema text,
    hh_aggregationunit_attr_owns boolean,
    hh_aggregationunit_fk text,
    hh_aggregationunit_href text,
    hh_healthservicetype_attr_owns boolean,
    hh_healthservicetype_attr_nilreason text,
    hh_healthservicetype_attr_gml_remoteschema text,
    hh_healthservicetype_fk text,
    hh_healthservicetype_href text,
    hh_healthservicevalue numeric,
    hh_referenceperiod_hh_referenceperiodtype_hh_startdate date,
    hh_referenceperiod_hh_referenceperiodtype_hh_enddate date,
    CONSTRAINT hh_healthservicesstatistic_pkey PRIMARY KEY (attr_gml_id)
);
